import { describe, expect, it } from "vitest"
import * as animations from "./index"

describe("package barrel", () => {
    it("exports dualRaf, tween, and the heavy-motion lock", () => {
        expect(typeof animations.dualRaf).toBe("function")
        expect(typeof animations.tween).toBe("function")
        expect(typeof animations.createHeavyAnimationLock).toBe("function")
        expect(animations.DEFAULT_HEAVY_LOCK_TIMEOUT_MS).toBe(1000)
        expect(typeof animations.queueMeasure).toBe("function")
        expect(typeof animations.queueMutate).toBe("function")
        expect(typeof animations.queueMeasureAfterMutate).toBe("function")
        expect(typeof animations.flushDomSchedule).toBe("function")
        expect(typeof animations.onAnimationFrame).toBe("function")
        expect(typeof animations.createViewSlide).toBe("function")
        expect(typeof animations.createListReorder).toBe("function")
        expect(typeof animations.createFade).toBe("function")
        expect(typeof animations.createStackLayer).toBe("function")
        expect(typeof animations.createSharedElement).toBe("function")
        expect(typeof animations.playSharedElement).toBe("function")
        expect(typeof animations.createCancelGroup).toBe("function")
        expect(typeof animations.createLayoutSizeTween).toBe("function")
        expect(typeof animations.createLayoutGrow).toBe("function")
        expect(typeof animations.canAnimateFull).toBe("function")
        expect(typeof animations.createOffsetDrag).toBe("function")
        expect(typeof animations.resolveDragAxis).toBe("function")
        expect(typeof animations.createOverscrollBounce).toBe("function")
        expect(animations.OVERSCROLL_COEFF).toBe(0.55)
        expect(animations.OVERSCROLL_APPKIT_STIFFNESS).toBe(20)
        expect(typeof animations.rubberBandAppKit).toBe("function")
        expect(typeof animations.elasticOverscrollAt).toBe("function")
        expect(typeof animations.rubberBandOverscroll).toBe("function")
    })

    it("re-exports motion timing tokens and aliases", () => {
        expect(animations.MOTION_UI_MS).toBe(200)
        expect(animations.MOTION_NAV_MS).toBe(350)
        expect(animations.FADE_MS).toBe(animations.MOTION_UI_MS)
        expect(animations.STACK_LAYER_MS).toBe(animations.MOTION_UI_MS)
        expect(animations.SHARED_ELEMENT_MS).toBe(animations.MOTION_NAV_MS)
        expect(animations.MOTION_HERO_EASE).toBe("cubic-bezier(0.38, 0.70, 0.125, 1)")
        expect(animations.MOTION_SPRING_EASE).toBe("cubic-bezier(0.2, 0.8, 0.2, 1)")
        expect(animations.SEND_FLIGHT_MS).toBe(animations.MOTION_NAV_MS)
        expect(animations.LAYOUT_GROW_MS).toBe(animations.MOTION_SETTLE_MS)
        expect(animations.SWIPE_TWEEN_MS).toBe(animations.MOTION_SETTLE_MS)
        expect(animations.SCROLL_TWEEN_MS).toBe(animations.MOTION_SETTLE_MS)
        expect(animations.WHEEL_RELEASE_MS).toBe(140)
        expect(animations.WHEEL_MOMENTUM_WINDOW).toBe(4)
        expect(animations.DRAG_LOCK_PX).toBe(10)
    })
})
